### ISSUE TITLE
 refresh session error: Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by choukin** [nswbmw/N-club#17]
```javascript
 koa-generic-session:session session id not exist, generate a new one +10s
  koa-route GET /signup matches /signup [] +5ms

  koa-generic-session:session new session and do not modified +4ms
  koa-generic-session:session refresh session error: Cannot read property 'done' of undefined +1ms
  xxx GET /signup 500 13ms -

  TypeError: Cannot read property 'done' of undefined
      at next (/work/learn/learnkoa/node_modules/co/index.js:98:14)
      at onFulfilled (/work/learn/learnkoa/node_modules/co/index.js:69:7)
      at /work/learn/learnkoa/node_modules/co/index.js:54:5
      at Object.co (/work/learn/learnkoa/node_modules/co/index.js:50:10)
      at Object.toPromise (/work/learn/learnkoa/node_modules/co/index.js:118:63)
      at next (/work/learn/learnkoa/node_modules/co/index.js:99:29)
      at onFulfilled (/work/learn/learnkoa/node_modules/co/index.js:69:7)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  <-- GET /favicon.ico
  koa-generic-session:session session id not exist, generate a new one +176ms
  koa-generic-session:session new session and do not modified +6ms
  koa-generic-session:session refresh session error: Cannot read property 'done' of undefined +0ms
  xxx GET /favicon.ico 500 8ms -

  TypeError: Cannot read property 'done' of undefined
      at next (/work/learn/learnkoa/node_modules/co/index.js:98:14)
      at onFulfilled (/work/learn/learnkoa/node_modules/co/index.js:69:7)
      at /work/learn/learnkoa/node_modules/co/index.js:54:5
      at Object.co (/work/learn/learnkoa/node_modules/co/index.js:50:10)
      at Object.toPromise (/work/learn/learnkoa/node_modules/co/index.js:118:63)
      at next (/work/learn/learnkoa/node_modules/co/index.js:99:29)
      at onFulfilled (/work/learn/learnkoa/node_modules/co/index.js:69:7)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

mac 笔记本，启动后 访问http://localhost:3000/signup

就会报上面的问题,

@nswbmw

**Comment by MidiGeek** [comment]
在co的issues中已经提出过这个问题，把脚本从"start": "NODE_ENV=default DEBUG=* node --harmony app",改为"start": "NODE_ENV=default DEBUG=* node app",就好了。去掉--harmony参数

**Comment by xiaoji201509** [comment]
请问你找到解决办法了吗
