### ISSUE TITLE
   SyntaxError: Invalid Unicode escape sequence in "index.ejs"

### ISSUE THREAD

**Issue by xiatian2475** [nswbmw/N-club#19]
Server listening on:  3000
  <-- GET /
  xxx GET / 500 158ms -

  SyntaxError: Invalid Unicode escape sequence in "index.ejs"
      at exports.compile (D:\node\N-club-master\node_modules\.1.5.2@co-ejs\lib\ejs.js:339:15)
      at exports.render (D:\node\N-club-master\node_modules\.1.5.2@co-ejs\lib\ejs.js:381:66)
      at next (native)
      at exports.renderFile (D:\node\N-club-master\node_modules\.1.5.2@co-ejs\lib\ejs.js:412:17)
      at next (native)
      at Object.app.context.render (D:\node\N-club-master\node_modules\.1.5.2@co-ejs\lib\ejs.js:167:23)
      at next (native)
      at onFulfilled (D:\node\N-club-master\node_modules\.4.6.0@co\index.js:65:19)

**Comment by lightColour** [comment]
I met the same question

**Comment by lightColour** [comment]
在userCard.ejs这个文件下，把<% var userInfo = yield $User.getUserByName(name) %>包含到div里就可以了
